yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'


urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('post_create/', views.post_create, name='post_create'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        verbose_name='Информация о группах',
        max_length=200
    )
    slug = models.SlugField(
        max_length=200, unique=True,
        db_index=True, verbose_name='slug'
    )
    description = models.TextField(
        verbose_name='Описание'
    )

    class Meta:
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        max_length=200, verbose_name='Текст',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True, verbose_name='Дата'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group, blank=True, null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:30]

yatube/posts/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
             'text': 'Текс поста',
             'group': 'Гуппа к которой будет относится ваш пост' 
        }

    

yatube/posts/views.py
from multiprocessing import context
from django.conf import settings
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic.base import TemplateView 
from django.contrib.auth.decorators import login_required
from .models import  Group, Post, User
from .forms import PostForm


def index(request):
    post_list = Post.objects.select_related('author', 'group')
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    } 
    return render(request, 'posts/index.html', context)

def group_posts(request, slug): 
    group = get_object_or_404(Group, slug=slug) 
    post_list = group.posts.select_related('author')
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = { 
        'title': 'Здесь будет информация о группах проекта Yatube',
        'group': group, 
        'page_obj': page_obj, 
    } 
    return render(request, 'posts/group_list.html', context) 


def profile(request, username):
    author = get_object_or_404(User, username=username)
    user_posts = author.posts.select_related('group')
    post_count = user_posts.count()
    paginator = Paginator(user_posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    title = f'Профаил пользователя {username}'
    context = {
        'title': title,
        'page_obj': page_obj,
        'post_count': post_count,
        'author': author, 
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    author_post = post.author
    post_count = Post.objects.filter(author=author_post).count()
    title = f'Пост {post.text[0:30]}'
    context = {
        'post': post,
        'post_count': post_count,
        'title': title,
        'author_post': author_post,
    }
    return render(request, 'posts/post_detail.html', context)

@login_required 
def post_create(request):
    is_edit = False
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    context = {
        'form': form,
        'is_edit': is_edit,
    }
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author)  
    return render(request, 'posts/post_create.html', context) 

@login_required
def post_edit(request, post_id):
    is_edit = True
    #form = PostForm(request.POST)
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post.id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post.id)
    context = { 
        'form': form,
        'is_edit': is_edit,
        'post': post,
    }

    return render(request, 'posts/post_create.html', context)
 
    
    
    

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} Записи сообщества; {{ group.title }}{% endblock %}
{% block content %}
{% load thumbnail %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>
      Записи сообщества; {{ group.description|linebreaks }}
    </p>
    {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }} 
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "450x270" crop="center" as im %}
      <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
      {% endthumbnail %}     
    <p>
      {{ post.text|linebreaks }} 
    </p>
    <a href="{% url 'posts:post_detail' post.id %}"> Подробная информация </a><br>
    <a href="{% url 'posts:profile' post.author %}"> Все посты пользователя</a><br> 
    {% if not forloop.last %}<hr>{% endif %}
    </article>  
    {% endfor %}
    {% include 'includes/paginator.html' %}
    <hr>
  </div>  
  {% endblock %} 

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
{% load thumbnail %}
<div class="container py-5">
  {% include 'includes/paginator.html' %}
  <h2>Главная страница</h2>
  {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }} 
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          <p>
            {{ post.text|linebreaksbr }}
          <p>  
          <!--<p ">-->
            {% thumbnail post.image "450x270" crop="center" as im %}
              <img style="border-style: solid;" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
            {% endthumbnail %}
          <p>
          <a href="{% url 'posts:post_detail' post.id %}"> Подробная информация </a><br>
          <a href="{% url 'posts:profile' post.author %}"> Все посты пользователя</a><br> 
          {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}"> Все записи группы {{ post.group.title }}</a> 
          {% if not forloop.last %}<hr>{% endif %}
        {% endif %}  
      </article>
  {% endfor %}
  {% include 'includes/paginator.html' %}
  <hr>
</div>
{% endblock %}

yatube/templates/posts/post_create.html
{% extends 'base.html' %}
{% load user_filters %}
{% block title %}
{% with request.resolver_match.view_name as view_name %}
{% if view_name == 'posts:post_create' %}
Новый пост
{% else %}
Редактор поста
{% endif %}
{% endwith %}
{% endblock %}  
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}      
            Редактируемый пост
          {% else %}
            Новый пост
          {% endif %}                 
        </div>
        <div class="card-body">        
          <form method="post" enctype="multipart/form-data" action="{% if is_edit %}{% url 'posts:post_edit' post.id %}
          {% else %}{% url 'posts:post_create' %}{% endif %}">
          {% csrf_token %}
          {% for field in form %}
          <div class="form-group row my-3"
          {% if field.field.required %}
            aria-required="true"
          {% else %}
            aria-required="false"
          {% endif %}
          >
          <label for="{{ field.id_for_label }}">
            {{ field.label }}
              {% if field.field.required %}
                <span class="required text-danger">*</span>
              {% endif %}
          </label>
          <div>
            {{ field|addclass:'form-control' }}
            {% if field.help_text %}
              <small id="{{ field.id_for_label }}-help" class="form-text-muted">
                {{ field.help_text|safe }}
              </small>
            {% endif %}
          </div>
          </div>  
          {% endfor %}       
            <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">
              {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %} 
            </button>
            </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>   
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
{% load thumbnail %}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:"d E Y" }} 
      </li>
        {% if post.group %}
      <li class="list-group-item">
        Группа: {{ post.group }}
        <a href="{% url 'posts:group_list' post.group.slug %}">
          все записи группы
        </a>
        {% endif %}
      </li>
      <li class="list-group-item">
        Автор: {{ author_post }},  id: {{ post.id }}
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора:  <span >{{ post_count }}</span>
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:profile' post.author %}">
          все посты пользователя
        </a>
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:post_edit' post.id %}">
          Редактировать пост
        </a>
      </li>  
    </ul>
  </aside>
  <article class="col-12 col-md-9">
  <p>
    {{ post.text|linebreaksbr }} 
  </p>
  <p style="border-style: solid;">
  {% thumbnail post.image "450x275" crop="center" as im %}
  <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
  {% endthumbnail %}
  </p>
  </article>
</div>        
{% endblock %}    

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}
Профайл пользователя {{ user.username }}
{% endblock %}
{% block content %}
{% load thumbnail %}
<div class="container ru-5">   
  <h2>Все посты пользователя {{ author.get_full_name }}</h2>
  <h3>Всего постов: {{ post_count }} </h3>
  {% for post in page_obj %}
  <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "450x275" crop="center" as im %}
    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
    {% endthumbnail %} 
    <p>{{ post.text|linebreaksbr }}</p>
  <a href="{% url 'posts:post_detail' post.id %}"> подробная информация </a>
  </article>
  {% if post.group %}   
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы, {{ post.group.slug }}</a>
  {% endif %} 
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %} 
  {% include 'includes/paginator.html' %}
</div>  
{% endblock %}